version: '3.9'

services:
  java_db:
    container_name: run_the_bank
    image: postgres:12
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: run_the_bank
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}